### PR TITLE
Add ubuntu 24.04

### PR DESCRIPTION
**Pull request by markfeathers**

### CODE REVIEW

**Comment by ts-kris** [comment]
Block this merge until https://github.com/embeddedTS/linux-lts/pull/119 is merged so we can bump all boards to latest 6.6 with those fixups applied.

**Review by randytsi369 — APPROVED** [review]
Reviewed, not tested.

**Review by luckshot — COMMENTED** [review]
Blocking merge till #119 is merged.

**Comment by markfeathers** [comment]
the linux-lts changes were merged, so bringing this in.

**Pull request merged**
